### PR TITLE
[MONDRIAN-2705] [MONDRIAN-2692] Fix Snowflake DECIMAL SqlStatment type

### PR DESCRIPTION
**Pull request by bennychow**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@peterrinehart Hi Peter, could you review and merge this?  I verified all Mondrian tests pass.  I also verified Mondrian's SQL generation with Snowflake double and number types.  See the JIRA for more info.  https://jira.pentaho.com/browse/MONDRIAN-2705?focusedCommentId=406195&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-406195  Thanks

**Comment by bennychow** [comment]
@peterrinehart @lucboudreau Hi Guys, could one of you merge this for 9.2 release?  Thanks

**Review by lucboudreau — APPROVED** [review]
Oof. That's a silly bug. Approved.

**Pull request merged**
