### PR TITLE
[MONDRIAN-2687] Poor performance with Execution context initialization

### PR DESCRIPTION
**Pull request by bennychow**

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 22m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>mondrian.olap.fun.sort.SorterTest.testCancel</b> (click to expand)</summary><p>

```

Wanted but not invoked:
execution.checkCancelOrTimeout();
-> at mondrian.olap.fun.sort.SorterTest.testCancel(SorterTest.java:135)
Actually, there were zero interactions with this mock.

```

</p></details>

<details><summary><b>mondrian.rolap.aggmatcher.SpeciesNonCollapsedAggTest.testBugMondrian1105</b> (click to expand)</summary><p>

```
Mondrian Error:Internal error: Error while executing query [select {[Measures].[Population]} ON COLUMNS,
  {[Animal.Animals].[Family].Members} ON ROWS
from [Test]
]
```

</p></details>

  
Tests run: **3704**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1219/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 11m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@mkambol @lucboudreau  Do you guys know why sometimes Wingman does not run the Mondrian ITs?  For example, the above run did not run the ITs, whereas earlier in the same day, the ITs did run:

http://wingman.pentaho.net/blue/organizations/jenkins/projects%2Fmondrian/detail/PR-1219/3/pipeline

**Pull request closed without merging**
