### PR TITLE
Addresses BACKLOG-40293: datasource info extraction

### PR DESCRIPTION
**Pull request by afrjorge**
@pentaho/millenniumfalcon please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 3m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by mbrasil — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 4m
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 4m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 5m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 24m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3307**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/mondrian/job/PR-1383/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by mbrasil — APPROVED** [review]

**Review by davidmsantos90 — APPROVED** [review]

**Pull request merged**
