### PR TITLE
[PDI-16624]-Big Number fields are not correctly aggregated in DET. Added a new PdiDataServiceDialect

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**
Divided into 2 commits in order not to confuse pr changes with checkstyle

### CODE REVIEW

**Comment by ArtsiomYurhevich** [comment]
@mkambol , @mbatchelor Could you please review the reworked solution. Thanks

**Comment by mkambol** [comment]
I think this looks good.  
For style, though-- I believe we're still using the non-pentaho "checkFile" conventions for Mondrian.  @lucboudreau, is that true?  Also, @lucboudreau - anything else to consider when creating a new dialect then what @ArtsiomYurhevich has done?

**Comment by lucboudreau** [comment]
Please use Mondrian's coding standard with the bin/checkStyle utility.

You will also need to add the dialect name in mondrian.xml and mondrian_sw.xml.

**Comment by ArtsiomYurhevich** [comment]
@mkambol , @lucboudreau Done

**Comment by lucboudreau** [comment]
Looks good.

Side question, is there a jira case to fix those tests?

**Pull request merged**
