### PR TITLE
[MONDRIAN-2250] - Inconsistent results in MDX Query

### PR DESCRIPTION
**Pull request by YuryBY**
@lucboudreau, take a look, please

### CODE REVIEW

**Comment by lucboudreau** [comment]
@kurtwalker Please review this change. Thanks!

**Comment by kurtwalker** [comment]
@lucboudreau @YuryBY it takes 40 seconds longer for me to run through the test suite with this change.  Are there any other options for fixing the bug?

**Comment by lucboudreau** [comment]
@YuryBY Please see @kurtwalker comments and try caching the hash code once generated. Ideally, it should be computed in the constructor and stored in a final variable, if possible.

**Comment by YuryBY** [comment]
@lucboudreau,  @kurtwalker PR is updated.

Now is used ancestor's hashCode which is cashed.

**Pull request merged**
