### PR TITLE
MONDRIAN-1342 Change the logging level of "mondrian.rolap.RolapUtil -…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
MONDRIAN-1342 Change the logging level of "mondrian.rolap.RolapUtil add sql statement logger

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@lucboudreau @pamval @kurtwalker @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@lucboudreau @pamval @kurtwalker @mchen-len-son please review

**Comment by lucboudreau** [comment]
What is this trying to address exactly?

**Comment by lucboudreau** [comment]
@bennychow Benny, There's this pull request, and then this other one. I'm not sure what's being fixed here. Can you please review both and make sure we're not creating any regressions? Plus, I doubt that we want to send SQL queries somewhere else in this case. 

ref: https://github.com/pentaho/pentaho-analyzer/pull/1090

**Comment by stanislau-strelchanka** [comment]
@lucboudreau @pamval @kurtwalker @mchen-len-son @bennychow  please review

**Pull request merged**
