### PR TITLE
[MONDRIAN-2683] Hang in mondrian.olap.fun.FunUtil.sortTuples

### PR DESCRIPTION
**Pull request by mkambol**
This commit extracts and refactors sorting logic from
FunUtil and moves it into a new mondrian.olap.fun.sort
package.

The main performance improvement is contained in
TupleExpMemoComparator:
1) The implementation formerly memoized evaluation results in a HashMap,
 which could result in memory thrashing with sufficiently large tuple lists.
 Replaced this with a guava Cache with a max size.
2) Formerly, values in the comparator were pre-loaded before the sort happened.
 For multi-level sorts, this had the potential to be overly aggressive, since
 not all sort keys may be hit.
3) A common sort use case is sorting on MEMBERKEY.  If a tuple consists of
 multiple hierarchies, only 1 is applicable for the MEMBERKEY sort.  This
 change checks the .depedentHierarchies() for each calc, stripping out
 unnecessary hierarchies.  This can have a dramatic impact on performance,
 since lists of huge crossproducts can be collapsed down to a much smaller
 evaluation space.

https://jira.pentaho.com/browse/MONDRIAN-2683

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 14m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by mkambol** [comment]
The "new" issues flagged by Sonar are actually old-- moving code around caused sonar to flag them.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 14m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
