### PR TITLE
Introduce Locus.isEmpty to prevent exceptions

### PR DESCRIPTION
**Pull request by blacelle**
Hello. We observe queries execution time from 10sec to 2 seconds by not trying to peek from Lokus when it is empty

### CODE REVIEW

**Comment by lucboudreau** [comment]
We cannot accept this change. A Locus is required for all executions. We need to be able to channel logs and events back to the parent mondrian instance, and the Locus carries this information.

If you're running into an issue where the locus is not set, I'm guessing that you are accessing the schema API directly. I suggest using withLocus() on the schema reader object. Does this correspond to what you are doing? Can you explain where and how you are seeing the empty Locus?

**Comment by blacelle** [comment]
In my case (a simple drilldown query from Excel), I indeed encountered an empty collection of Locus. Not manipulating the schema API directly

**Comment by lucboudreau** [comment]
Can you share a stack trace with us please? It would be a bug if this happens from inside of Mondrian.

**Comment by lucboudreau** [comment]
Closing for now. Locus should never be empty. Let's discuss this in a Jira ticket instead.

https://jira.pentaho.com

**Pull request closed without merging**
