### PR TITLE
[MONDRIAN-2534]: Mondrian CancellationChecker.checkCancelOrTimeout does not terminate thread

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
Fixed according to the comment in the jira, added unit tests.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@lucboudreau , please take a look.
There are one failed test: org.olap4j.CellSetFormatterTest.testEmptyRowsRectangular that is placed in https://github.com/olap4j/olap4j
What should I do with this one?

**Comment by lucboudreau** [comment]
Not sure how a timeout change makes the parser fail. Should be investigated. I don't think the test is at fault here.

**Comment by TatsianaKasiankova** [comment]
@mkambol, @kurtwalker  please review.

**Comment by TatsianaKasiankova** [comment]
@lucboudreau , @mkambol, @kurtwalker Hi all
I've investigated the failed test `org.olap4j.CellSetFormatterTest.testEmptyRowsRectangular` in the [previous run](https://github.com/pentaho/mondrian/pull/970#issuecomment-338705774):  
The test indicates on the issue with absent Locus in execution context for olap4j MondrianOlap4jCellSetAxis.
This problem also was reproduced via Analyzer MDX runner.
So I've placed a Locus in the execution context for MondrianOlap4jCellSetAxis on getting axis positions size to fix it.
Now all olap4j Test Compatibility Kit (TCK) tests are passed.
Please review one more time.

**Comment by lucboudreau** [comment]
Hi Tatsiana, sorry for the delay reviewing this. Good catch btw.

One last thing. Please use Mondrian's coding style. You can validate your changes using the ./bin/checkStyle utility.

**Comment by TatsianaKasiankova** [comment]
@lucboudreau I've checked files in my PR with `./bin/checkStyle ` and fixed problems.
Please merge it.

**Pull request merged**
