### PR TITLE
[MONDRIAN-366] BottomCount bug

### PR DESCRIPTION
**Pull request by gryphendowre**
* Added code suggested in JIRA ticket. Verified that it should act like Tail MDX query in unordered listing.
* Added test code to verify query retrieval

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by gryphendowre** [comment]
Working on another commit to cleanup code atm

**Comment by buildguy** [comment]
### :x: Build failed in 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@gryphendowre Code changes look good to me.  I think it would be cleaner to combine the two commits.  Also, it'll make backporting easier since there would only be one commit to cherry pick.

**Comment by mkambol** [comment]
@bennychow -  I had suggested splitting out the cleanup commit because it's pretty hard to tell what really changed when digging through formatting stuff.
If there ends up being a backport for this, the functional commit came first, so should cleanly merge in the 9.0 / 8.3 branches.

**Pull request merged**
