### PR TITLE
MONDRIAN-2252 -- Ord.java seems to have wrong / missing license attributi...

### PR DESCRIPTION
**Pull request by kolinus**
...on

What was done:
1) Changed license header

### CODE REVIEW

**Comment by lucboudreau** [comment]
There is a typo in the commit message. 

Also, please merge this into branch 'lagunitas', 4.1 and 4.2 as well. Thanks.

**Comment by kolinus** [comment]
@lucboudreau fixed typo,
4.1 https://github.com/pentaho/mondrian/pull/450
4.2 https://github.com/pentaho/mondrian/pull/451
4.2.0.2 https://github.com/pentaho/mondrian/pull/452
lagunitas  https://github.com/pentaho/mondrian/pull/453

**Comment by lucboudreau** [comment]
I meant a typo in the commit message itself, not the pull request. (notice the missing N :)

Also, please use the bracket-style: "[MONDRIAN-2252] ..." instead of "MODRIAN-2252 ..."

**Comment by kolinus** [comment]
done

**Comment by lucboudreau** [comment]
All merged. Thank you sir.

**Pull request merged**
