### PR TITLE
[MONDRIAN-2157] - TopPercent() get a NullPointerException

### PR DESCRIPTION
**Pull request by YuryBY**
@mkambol, @lucboudreau, take a look, please

### CODE REVIEW

**Comment by lucboudreau** [comment]
@pamval This case isn't included in 6.0. It has no fix version. Can you figure this one out with David? I'm at a customer site all week and the cutoff is near.

**Comment by pamval** [comment]
@lucboudreau this is part of the October Service Pack (you can see that in the Active Sprint).

**Comment by pamval** [comment]
Assigning to Matt since Luc is busy.

**Comment by mkambol** [comment]
@YuryBY I think your fix looks right.  Can you move your test into FunctionTest, though?  There are many other similar tests in that class and it's easier to keep them together.

**Comment by YuryBY** [comment]
@mkambol, the changes are done

**Pull request merged**
