### PR TITLE
[MONDRIAN-2082] Add support for correlating logged SQL and logged MDX…

### PR DESCRIPTION
**Pull request by bennychow**
… via MDC

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 17m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3706**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1248/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3706**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1248/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@lucboudreau Hi Luc, could you help review these changes for https://jira.pentaho.com/browse/BISERVER-5014 and https://jira.pentaho.com/browse/MONDRIAN-2082?  It looks like you did some work on this in the past.  Thanks

@mkambol 

@dcleao @rmansoor FYI...

**Comment by bennychow** [comment]
Note: All 3706 Mondrian ITs pass locally and on Wingman.

**Review by lucboudreau — APPROVED** [review]
Great job.

I thought we already had some bits related to MDC in there but I can't find them anymore.

Also, I'm not 100% certain, but I think this may break pentaho-analysis-ee. Did you get a chance to check?

**Comment by bennychow** [comment]
> Great job.
> 
> I thought we already had some bits related to MDC in there but I can't find them anymore.
> 
> Also, I'm not 100% certain, but I think this may break pentaho-analysis-ee. Did you get a chance to check?

Thanks Luc.  We did have bits of MDC in there before but I cleaned it up and made it more re-usable.  I'll double check on pentaho-analysis-ee.

**Comment by bennychow** [comment]
@lucboudreau I tested the external Segment cache using PentahoPlatformSegmentCache and I verified that the MDC properties were being logged correctly.  See below.  If all looks good, could you help me merge this PR?  Thanks

```
2020-11-07 12:20:52,043 DEBUG [mondrian.rolap.RolapUtil] sessionId:C7940F689F9D3FD5C8F447BE83386C95 sessionName:admin instanceId:bb3e87c2-2136-11eb-9a6a-cc3d826f68f5 remoteAddr:0:0:0:0:0:0:0:1 Saving segment into SegmentCache com.pentaho.analysis.segmentcache.impl.pentaho.PentahoPlatformSegmentCache.
Header:
*Segment Header
Schema:[SampleData]
Checksum:[cb9ecfa6ddf75a585e69d2a452c2f500]
Cube:[Quadrant Analysis]
Measure:[Actual]
Axes:[
    {POSITIONTITLE=(*)}]
Excluded Regions:[]
Compound Predicates:[]
ID:[3e38945db9f432a6b5fe70d413ec43cb80c3eba8d93270a73857bf6ae6af8ee5]
```

**Comment by lucboudreau** [comment]
@bennychow Merged.

**Pull request merged**
