### PR TITLE
[MONDRIAN-2535] Virtual Cube dimensions incorrectly flagged as degene…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…rate

### CODE REVIEW

**Comment by ivanpogodin** [comment]
@lucboudreau , could you take a look, please?
Is the assert correct? (https://github.com/pentaho/mondrian/pull/858/files#diff-5132a8377cb4e42f972dd81821d04ae7R74)

**Comment by mchen-len-son** [comment]
@mbatchelor, @lucboudreau @kurtwalker  can you please take a look?
thanks.

**Comment by mchen-len-son** [comment]
Build seems to be OK - the tests passed, something was wrong after that.
Locally this error is not reproduced.
Checkstyle is also ok.

**Comment by mkambol** [comment]
Tests?

**Comment by ivanpogodin** [comment]
@mbatchelor, @lucboudreau , @kurtwalker can you please take a look?
Changed classes - mondrian.rolap.RolapCubeDimension , mondrian.rolap.RolapCubeHierarchy

**Pull request merged**
