### PR TITLE
Fixes for MONDRIAN-2719 and MONDRIAN-2721

### PR DESCRIPTION
**Pull request by bennychow**
[MONDRIAN-2719] Performance issues when Mondrian is dealing with large slicer
[MONDRIAN-2721] Incorrect counters in MondrianMonitor

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@lucboudreau Hi Luc, could you help review and merge this?  Thanks

**Comment by bennychow** [comment]
@dcleao Please help review and merge this.  Thanks!

**Review by dcleao — APPROVED** [review]

**Pull request merged**
