### PR TITLE
[MONDRIAN-2684] Improve Mondrian explain plan and timing features

### PR DESCRIPTION
**Pull request by bennychow**
[ANALYZER-4016] Improve performance of Aggregate subtotals

### CODE REVIEW

**Comment by bennychow** [comment]
After further review with Carlos on the query plan output and additional performance problem use cases, the following improvements were made:
- Subtotal performance - Need to make the compound slicer member solve configurable and default to -99999 so that it works with Analyzer's Aggregate total solve order of -100.  See ANALYZER-4016 for the performance impact.
- Fix double counting of time in QueryTiming when the same function is called within itself
- Add QueryTimings for all Analyzer subtotal types (MIN, MAX, AVG and COUNT)
- Add expression cache hit and miss counters for measuring slicer cacheCalc and CACHE MDX function improvement
- Breakdown the query profiling by Filter Axis, Column Axis, Row Axis and Query Body
- Moved explain plan related tests to a new class

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3716**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1253/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3716**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1253/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@lucboudreau Hi Luc,  could you review these additional changes?  I listed each item above.  There's a bunch of changes coming in Analyzer too that leverages this stuff.  We're making a huge improvement in Analyzer query timing and performance this release.

**Review by lucboudreau — APPROVED** [review]

**Pull request merged**
