### PR TITLE
[MONDRIAN-2610] - Error with UCase function

### PR DESCRIPTION
**Pull request by YuryBY**
- JUnit tests are provided

### CODE REVIEW

**Comment by YuryBY** [comment]
@lucboudreau, @mkambol, could you please take a look? - local CI shows the same broken tests for master branch and it does not seem like relates to the changes.

**Comment by lucboudreau** [comment]
So.. Will those tests ever get fixed, or will you guys always ignore them for every single pull request?

**Comment by YuryBY** [comment]
@lucboudreau , @mkambol , @kurtwalker, @duarteteixeira please take a look.
The Broken Tests above are failed from time to time on Wingman, although the same tests are passed successfully on the other env (please see reported issue for this case http://jira.pentaho.com/browse/BACKLOG-18779). So that please triage the ticket and add it to our board in order we have possibility to start work on this.

**Comment by kurtwalker** [comment]
Since there is a case written up, can we disable the tests until the case is picked up?

**Pull request merged**
