### PR TITLE
[MONDRIAN-2443] Properties of type float not formatted properly from …

### PR DESCRIPTION
**Pull request by mchen-len-son**
…a SQL Server DB

- fixed rolap member property formatting
- added unit test

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@lucboudreau, @mkambol, @pamval 

Guys, please, take a look a the changes.

I see the previous formatting implementation was locale-insensitive due to _BigDecimal.toString_ javadoc. So I left this behavior unchanged.
But, is this correct? Maybe we should make it locale-sensitive?

**Comment by mkambol** [comment]
One thing I'd hope to see is that a numeric column used as a member caption should have the same formatting as if that column were used instead as a member property-- we should be consistent.  I could be wrong, but I think numeric member captions would not get wrapped by BigDecimal in the same way and the formatting could be different.  Is that correct, @lucboudreau?

**Comment by mchen-len-son** [comment]
@lucboudreau 

Did you have a chance to take a look at the PR?

**Comment by lucboudreau** [comment]
Had to do a bit of research. I was a bit worried about using a String representation with ``val.toString()``, but my previous code was even worse, and is introducing loss of precision.

Anyhow, to Matt's comment, it would be nice to apply this logic to member captions as well. Although IIRC the code related to members uses a default implementation of ``MemberFormatter``, unlike here, where the code is procedurally included when there are no formatters for the current property. 

If we're doing a true reconciliation of these, let's make sure they also share the same code. Refactor the default formatting of captions and properties into one method if possible (you will need to do a bit of research, there might be some different rules making this whole thing more work than required)

**Comment by mchen-len-son** [comment]
@mkambol, @lucboudreau, I've updated the changes. Review, please.
- added formatting for caption column numeric values

**Comment by mkambol** [comment]
Hey @mchen-len-son - looks good.

One thing, though, you'll need to add your new test class to mondrian.test.Main for it to be included in the test suite.

**Comment by mchen-len-son** [comment]
@mkambol, thanks. 
I've added test to the test suite.

**Pull request merged**
