### PR TITLE
Addresses BACKLOG-40293: add DISCOVER_XML_METADATA rowset

### PR DESCRIPTION
**Pull request by afrjorge**
@pentaho/millenniumfalcon please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 4m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs
```
---
:ok_hand: All tests passed!
 
Tests run: **1**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/mondrian/job/PR-1371/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 21m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 8 test(s) failed:

<details><summary><b>mondrian.test.DrillThroughTest.testDrillthroughNegativeMaxRowsFails</b> (click to expand)</summary><p>

```
query's error does not match pattern 'Syntax error at line 1, column 22, token '-''; error is [org.olap4j.OlapException: mondrian gave exception while parsing query
 at mondrian.olap4j.MondrianOlap4jConnection$Helper.createException(MondrianOlap4jConnection.java:845)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery2(MondrianOlap4jStatement.java:84)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery(MondrianOlap4jStatement.java:65)
 at mondrian.test.TestContext.executeStatement(TestContext.java:522)
 at mondrian.test.DrillThroughTest.testDrillthroughNegativeMaxRowsFails(DrillThroughTest.java:1355)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at junit.framework.TestCase.runTest(TestCase.java:154)
 at junit.framework.TestCase.runBare(TestCase.java:127)
 at junit.framework.TestResult$1.protect(TestResult.java:106)
 at junit.framework.TestResult.runProtected(TestResult.java:124)
 at junit.framework.TestResult.run(TestResult.java:109)
 at junit.framework.TestCase.run(TestCase.java:118)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.apache.maven.surefire.junit.JUnitTestSetExecutor.execute(JUnitTestSetExecutor.java:81)
 at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
 at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:93)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
 at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
 at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]
```

</p></details>

<details><summary><b>org.olap4j.ConnectionTest.testInvalidStatement</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>mondrian.xmla.XmlaBasicTest.testDSchemaRowsets</b> (click to expand)</summary><p>

```
expected:<......> but was:<...DISCOVER_XML_METADATA</SchemaName>
                        <Restrictions>
                            <Name>DatabaseID</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Restrictions>
                            <Name>ObjectExpansion</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Description>Returns an XML document describing a requested object. The rowset that is returned always consists of one row and one column.</Description>
                    </row>
                    <row>
                        <SchemaName>...>
```

</p></details>

<details><summary><b>mondrian.xmla.XmlaExcel2000Test.testExpect02</b> (click to expand)</summary><p>

```
expected:<......> but was:<...DISCOVER_XML_METADATA</SchemaName>
                        <Restrictions>
                            <Name>DatabaseID</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Restrictions>
                            <Name>ObjectExpansion</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Description>Returns an XML document describing a requested object. The rowset that is returned always consists of one row and one column.</Description>
                    </row>
                    <row>
                        <SchemaName>...>
```

</p></details>

<details><summary><b>mondrian.xmla.XmlaExcel2000Test.test02</b> (click to expand)</summary><p>

```
expected:<......> but was:<...DISCOVER_XML_METADATA</SchemaName>
                        <Restrictions>
                            <Name>DatabaseID</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Restrictions>
                            <Name>ObjectExpansion</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Description>Returns an XML document describing a requested object. The rowset that is returned always consists of one row and one column.</Description>
                    </row>
                    <row>
                        <SchemaName>...>
```

</p></details>

<details><summary><b>mondrian.xmla.XmlaExcelXPTest.testExpect02</b> (click to expand)</summary><p>

```
expected:<......> but was:<...DISCOVER_XML_METADATA</SchemaName>
                        <Restrictions>
                            <Name>DatabaseID</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Restrictions>
                            <Name>ObjectExpansion</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Description>Returns an XML document describing a requested object. The rowset that is returned always consists of one row and one column.</Description>
                    </row>
                    <row>
                        <SchemaName>...>
```

</p></details>

<details><summary><b>mondrian.xmla.XmlaExcelXPTest.test02</b> (click to expand)</summary><p>

```
expected:<......> but was:<...DISCOVER_XML_METADATA</SchemaName>
                        <Restrictions>
                            <Name>DatabaseID</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Restrictions>
                            <Name>ObjectExpansion</Name>
                            <Type>xsd:string</Type>
                        </Restrictions>
                        <Description>Returns an XML document describing a requested object. The rowset that is returned always consists of one row and one column.</Description>
                    </row>
                    <row>
                        <SchemaName>...>
```

</p></details>

<details><summary><b>mondrian.test.ExplainPlanTest.testExplainInvalid</b> (click to expand)</summary><p>

```
query's error does not match pattern 'MDX object '[Measures].[Store Margin]' not found in cube 'Sales''; error is [org.olap4j.OlapException: mondrian gave exception while parsing query
 at mondrian.olap4j.MondrianOlap4jConnection$Helper.createException(MondrianOlap4jConnection.java:845)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery2(MondrianOlap4jStatement.java:84)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery(MondrianOlap4jStatement.java:65)
 at mondrian.test.ExplainPlanTest.testExplainInvalid(ExplainPlanTest.java:193)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at junit.framework.TestCase.runTest(TestCase.java:154)
 at junit.framework.TestCase.runBare(TestCase.java:127)
 at junit.framework.TestResult$1.protect(TestResult.java:106)
 at junit.framework.TestResult.runProtected(TestResult.java:124)
 at junit.framework.TestResult.run(TestResult.java:109)
 at junit.framework.TestCase.run(TestCase.java:118)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.apache.maven.surefire.junit.JUnitTestSetExecutor.execute(JUnitTestSetExecutor.java:81)
 at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
 at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:93)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
 at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
 at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]
```

</p></details>

  
Tests run: **3519**, Failures: **8**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/mondrian/job/PR-1371/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by mbrasil — APPROVED** [review]

**Comment by mbrasil** [comment]
Nice job linting and removing the warnings!

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Review by davidmsantos90 — APPROVED** [review]

**Comment by buildguy** [comment]
### :warning: Build finished in 29m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.olap4j.ConnectionTest.testInvalidStatement</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>mondrian.test.DrillThroughTest.testDrillthroughNegativeMaxRowsFails</b> (click to expand)</summary><p>

```
query's error does not match pattern 'Syntax error at line 1, column 22, token '-''; error is [org.olap4j.OlapException: mondrian gave exception while parsing query
 at mondrian.olap4j.MondrianOlap4jConnection$Helper.createException(MondrianOlap4jConnection.java:845)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery2(MondrianOlap4jStatement.java:84)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery(MondrianOlap4jStatement.java:65)
 at mondrian.test.TestContext.executeStatement(TestContext.java:522)
 at mondrian.test.DrillThroughTest.testDrillthroughNegativeMaxRowsFails(DrillThroughTest.java:1355)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at junit.framework.TestCase.runTest(TestCase.java:154)
 at junit.framework.TestCase.runBare(TestCase.java:127)
 at junit.framework.TestResult$1.protect(TestResult.java:106)
 at junit.framework.TestResult.runProtected(TestResult.java:124)
 at junit.framework.TestResult.run(TestResult.java:109)
 at junit.framework.TestCase.run(TestCase.java:118)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.apache.maven.surefire.junit.JUnitTestSetExecutor.execute(JUnitTestSetExecutor.java:81)
 at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
 at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:93)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
 at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
 at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]
```

</p></details>

<details><summary><b>mondrian.test.ExplainPlanTest.testExplainInvalid</b> (click to expand)</summary><p>

```
query's error does not match pattern 'MDX object '[Measures].[Store Margin]' not found in cube 'Sales''; error is [org.olap4j.OlapException: mondrian gave exception while parsing query
 at mondrian.olap4j.MondrianOlap4jConnection$Helper.createException(MondrianOlap4jConnection.java:845)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery2(MondrianOlap4jStatement.java:84)
 at mondrian.olap4j.MondrianOlap4jStatement.executeQuery(MondrianOlap4jStatement.java:65)
 at mondrian.test.ExplainPlanTest.testExplainInvalid(ExplainPlanTest.java:193)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at junit.framework.TestCase.runTest(TestCase.java:154)
 at junit.framework.TestCase.runBare(TestCase.java:127)
 at junit.framework.TestResult$1.protect(TestResult.java:106)
 at junit.framework.TestResult.runProtected(TestResult.java:124)
 at junit.framework.TestResult.run(TestResult.java:109)
 at junit.framework.TestCase.run(TestCase.java:118)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.apache.maven.surefire.junit.JUnitTestSetExecutor.execute(JUnitTestSetExecutor.java:81)
 at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
 at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:93)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
 at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
 at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]
```

</p></details>

  
Tests run: **3519**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/mondrian/job/PR-1371/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 22m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 21m 44s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 22m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 31m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3519**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/mondrian/job/PR-1371/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
