### PR TITLE
[MONDRIAN-625] The Descendants function will only return Non Empty member children, even if it is not specified inside of NON EMPTY

### PR DESCRIPTION
**Pull request by Advent51**
Descendants function is NON EMPTY dependent now.

### CODE REVIEW

**Comment by Advent51** [comment]
Well, the problem with `NonEmptyTest.java` modification still persists: last wingman fail was caused by the modification of `testBugMondrian321` in `NonEmptyTest.java`

When I fixed the behavior of `descendantsByDepth` function, this test failed. But if we look at [MONDRIAN-321](http://jira.pentaho.com/browse/MONDRIAN-321) we can see that the previous expected result was wrong, because `NON EMPTY` wasn't specified on axis. (Without `NON EMPTY` but with my fix it returns result set with empty members as expected)

@lucboudreau @mkambol please review

**Comment by Advent51** [comment]
@lucboudreau @mkambol please review

**Comment by mkambol** [comment]
@Advent51 I think you're right-- testBugMondrian321 appears to be testing the opposite of what it's supposed to.
Can you fix that test?  It really should do something like verifySameNativeAndNot().

**Comment by Advent51** [comment]
@mkambol Actually I did that. Look at [this](https://github.com/pentaho/mondrian/pull/847/files#diff-b2ced3a3d22109e06eb8b00f4075bf60R4299)

**Comment by mkambol** [comment]
Sorry @Advent51, I don't follow.  Does testBugMondrian321 succeed or fail?  

Either way, that test seems like a good candidate to verify same results native and not.  .verifySameNativeAndNot() gives you a good way to do that.

**Comment by Advent51** [comment]
@mkambol please review.
I added `verifySameNativeAndNot()` test as you requested.

**Comment by Advent51** [comment]
@mkambol @lucboudreau please review

**Pull request merged**
