### PR TITLE
[MONDRIAN-2296] Invalid query results after executing crossjoin() query (integer measures)

### PR DESCRIPTION
**Pull request by labkey-matthewb**

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@labkey-matthewb, I've picked up your changes, add a couple of tests and sent a PR: https://github.com/pentaho/mondrian/pull/481

Thanks for an investigation!

**Comment by dkincade** [comment]
Please reissue the pull request...

**Comment by dkincade** [comment]
@lucboudreau please follow-up on this item...

**Comment by lucboudreau** [comment]
No need to reissue. This PR was superseded by #481 .

**Pull request closed without merging**
