### PR TITLE
[MONDRIAN-2713] Fix performance issue with empty aggregation lists ca…

### PR DESCRIPTION
**Pull request by bennychow**
…using cache misses across RolapEvaluators

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 15m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3720**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1255/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@lucboudreau Hi Luc, could you review and merge this?  I found a performance problem with my previous check-in on this same JIRA.  I was running my performance reports again and noticed they were running slower.  Then I checked the Query Timing output and StatementInfo numbers and was able to figure out there were a lot more calls to evalForSlicer and expCacheMisses.  This then led me to investigate these changes and I found this performance issue.

**Comment by lucboudreau** [comment]
Hi @bennychow , I don't mind reviewing those for you, but I think it'll be better if your team does this. Can someone on your end review and merge iot? If not let me know I'll get on it.

**Pull request merged**
