### PR TITLE
BACKLOG-5895 -- Expose Relational Information through Mondrian

### PR DESCRIPTION
**Pull request by kolinus**
Utility/Helper

What was done:
1) exposed xml description of RolapCubeDimension
2) added utility

### CODE REVIEW

**Comment by kolinus** [comment]
@kurtwalker @rfellows  could you please take a look

**Comment by kolinus** [comment]
@kurtwalker @lucboudreau  could you please review.

**Comment by lucboudreau** [comment]
Since the methods in ``DBInfoOlap4jHelper.java`` are all static, you might as well move the whole class in the ``mondrian.rolap`` package, then revert your scope changes to the other classes.

Secondly, why does this need to be in mondrian? Whatever uses this should have the class within it. It should work as long as it's in the same package, ``mondrian.rolap``.

**Comment by kolinus** [comment]
@lucboudreau Luc, currently we need this for analyzer where we have no mondrian packages.
Also this stuff is useless without mondrian, so it looks logical to be placed to mondrian.

**Comment by lucboudreau** [comment]
Please move this to Analyzer and create the missing package.

**Pull request closed without merging**
