### PR TITLE
[MONDRIAN-2634] Expose Level datatype through olap4j

### PR DESCRIPTION
**Pull request by bennychow**

### CODE REVIEW

**Comment by bennychow** [comment]
@lucboudreau Hi Luc,  this should be good for merge now.  Thanks.

**Comment by nantunes** [comment]
@bennychow and @lucboudreau : https://github.com/pentaho/pentaho-platform is broken with `[ERROR] extensions/src/main/java/org/pentaho/platform/plugin/action/olap/PlatformXmlaExtra.java:[53,8] org.pentaho.platform.plugin.action.olap.PlatformXmlaExtra is not abstract and does not override abstract method getLevelDataType(org.olap4j.metadata.Level) in mondrian.xmla.XmlaHandler.XmlaExtra`.

I didn't find any related PR there. Are you on it? Thanks.

**Comment by lucboudreau** [comment]
Just saw your comment. I'll fix it.

**Comment by lucboudreau** [comment]
Fixed it in #1063

**Pull request merged**
