### PR TITLE
[SP-5309] Backport of PSW-269 - Multiple dialects are missing from lists used in expressions (8.3 Suite)

### PR DESCRIPTION
**Pull request by LeonardoCoelho71950**
Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/mondrian/commit/ba0daf210a396c84791b368321392c1cee4eb162
* https://github.com/Pentaho/mondrian/commit/ec124f72246d11cbd523b4a6140ec289eeafa860
* https://github.com/pentaho/mondrian/commit/0bfb950a17387586f074ba1c635cf68989e16ef2

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian,workbench
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian,workbench
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl mondrian,workbench
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
Consistent with the base case. But shouldn't the typo have been corrected in Mondrian.xml as it was in Mondrian_SW.xml.
Asked Kurtis about it. Don't merge until we know if the base case is going to change also

**Pull request merged**
