### PR TITLE
[MONDRIAN-1398] The CurrentMember function should be disallowed when …

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[MONDRIAN-1398] The CurrentMember function should be disallowed when the dimension is in a compound slicer

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@mchen-len-son @kurtwalker @lucboudreau @mkambol please review

**Comment by lucboudreau** [comment]
@mkambol @stanislau-strelchanka I feel we could use a property to use the old behavior, although I'm hoping to have your thoughts on this as well. We have other fixes in place around disallowing certain calculations for exactitude's sake, and we've usually added a way to disable those checks. In this case, since the new behavior throws an exception, I'm inclined to add a legacy property. Thoughts?

**Comment by mkambol** [comment]
IIRC, the old behavior would return the null member for .CurrentMember, which is almost certainly not what would be expected.  Analysis Services will error out if you attempt to do it.
Given that it would be unusual to even attempt it, and results will be wrong if you do, I'd say a property would just add confusion.

**Comment by lucboudreau** [comment]
Other thing I wish I had caught earlier. We need to use the messages and errors bundles. We don't hard code error messages and exceptions into the code.

**Comment by mkambol** [comment]
Good point.  @stanislau-strelchanka - can you do a CLEANUP commit for that?

**Comment by mchen-len-son** [comment]
@mkambol, Stanislau is on vac - I will provide it

**Pull request merged**
