### PR TITLE
[MONDRIAN-2689] Regression with CurrentMember MDX function performanc…

### PR DESCRIPTION
**Pull request by bennychow**
…e with large slicers

### CODE REVIEW

**Comment by bennychow** [comment]
This fix improves the performance of large slicers in two areas.  

The first area is with the CurrentMember MDX function when the function tries to validate that the CurrentMember is not referencing a slicer that contains more than one member from the hierarchy. This improvement is to use a cached map to lookup the slicer members for a given hierarchy instead of doing an expensive iteration over all slicer members at the point of validation.

The second area is with RolapResult.AxisMemberList where de-duplicating slicer members was iterating over every member of the list.  The improvement is to also use a HashSet to quickly check for duplicates.

The above fixes were able to share code because the slicer members generated in RolapResult.AxisMemberList are set into the RolapEvaluator:

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 17m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3705**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1234/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@lucboudreau Here's a new PR that is able to use a HashSet and still keep the generated SQL deterministic.  All tests pass 100%.

@lucboudreau @mkambol @pentaho/ackbar   Please review and merge.  Thanks!

**Comment by bennychow** [comment]
On Matt's suggestion, I added a second commit which addresses the Sonar Checkstyle complaints.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -DrunITs -pl mondrian
```
---
:ok_hand: All tests passed!
 
Tests run: **3705**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/mondrian/job/PR-1234/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
