### PR TITLE
[SP-4132]: Backport of MONDRIAN-2604 - java.lang.ArrayIndexOutOfBoundsException while applying Filters. (7.1 Suite)

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
This is the back port of the fix for MONDRIAN-2604.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@stepanovdg , @mchen-len-son please review.

**Comment by TatsianaKasiankova** [comment]
@mchen-len-son, @pentaho-lmartins please review

**Comment by pentaho-lmartins** [comment]
@TatsianaKasiankova can you please replace Pentaho with Hitachi Vantara in the copyright?

**Comment by TatsianaKasiankova** [comment]
@pentaho-lmartins We did not change Pentaho to Hitachi Vantara in the copyright for 7.1 SPs before.
Has something changed?

**Comment by TatsianaKasiankova** [comment]
@pentaho-lmartins updated.

**Pull request merged**
