### PR TITLE
[ANALYZER-3728]-When Numeric Filter is set, Alert is displayed

### PR DESCRIPTION
**Pull request by denisprotopopov**
- fixed
- added unit test

### CODE REVIEW

**Comment by denisprotopopov** [comment]
@lucboudreau please review the changes

**Comment by lucboudreau** [comment]
We can't tell what changed in this PR. You are using the wrong code style. 

To check style for mondrian, go to the root of the repository and run:

```
./bin/checkStyle.sh --opened
```

**Comment by denisprotopopov** [comment]
@lucboudreau please review the changes

**Comment by denisprotopopov** [comment]
@lucboudreau please review the changes

**Pull request closed without merging**
