### PR TITLE
[MONDRIAN-2434] Drill-through filtering not properly working when dim…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[MONDRIAN-2434]ension level is excluded from filter and not displayed on canvas
- fix, for sql generation

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
added test, @kurtwalker, @lucboudreau, @mkambol, @mchen-len-son please review

**Comment by stanislau-strelchanka** [comment]
@kurtwalker, @lucboudreau, @mkambol, @mchen-len-son, wingman failed, could you please rerun it

**Comment by mkambol** [comment]
@stanislau-strelchanka wingman doesn't play nicely with mondrian yet.

**Comment by stanislau-strelchanka** [comment]
@mkambol got it, thanks for the info

**Pull request merged**
