### PR TITLE
[MONDRIAN-2425] - MDX will not stop at timeout for certain Analyzer r…

### PR DESCRIPTION
**Pull request by YuryBY**
…eports with totals/subtotals

@mkambol, would you mind of reviewing/merging?

### CODE REVIEW

**Comment by mkambol** [comment]
@YuryBY I don't think this will do it.  You've added a isCancelOrTimeout check within the loop, but nothing stops the loop (just the checkData).  Worse, calling isCancelOrTimeout won't actually trip the timeout flag-- it just checks whether it's already been set.  .checkCancelOrTimeout() will set the timeout state and throw a QueryTimeoutException.

We don't want to be doing this every time within a tight loop, though.  In SqlTupleReader we used the strategy of checking at a PhaseInterval.  That might work here.  But actually I think it might be preferable to just check once before we enter the cursor.forward loop.  In the cases where I've seen problems where we spend excessive time in checkData (like the ESR associated with this bug) there have been deeply nested crossjoins, so we hit nonEmptyList many times.

**Comment by YuryBY** [comment]
@mkambol, PR is updated. The timeout check is still in the loop since .checkDate on each iteration could be quite expensive. Let me know if it definitely should be moved out of the loop. Thanks.

**Comment by lucboudreau** [comment]
Let's not make it even slower... please use an interval.

**Comment by YuryBY** [comment]
@lucboudreau, already updated. Let me know if i have incorrectly understand what did you mean. Thanks.

**Comment by mkambol** [comment]
@YuryBY - using an interval is an improvement.  I don't think checking isCancelOrTimeout() is the best option, though-- using checkCancelOrTimeout() instead will check cancel/timeout and throw an appropriate exception if needed, also managing notification.

**Comment by YuryBY** [comment]
@mkambol, @lucboudreau, the update is done.Thanks.

**Comment by mbatchelor** [comment]
@mkambol and @YuryBY - I don't know why this was merged without any new test cases covering the behavior change.

**Comment by lucboudreau** [comment]
@mbatchelor Different PR.

https://github.com/pentaho/mondrian/pull/608

**Comment by lucboudreau** [comment]
Woops wrong PR.

**Comment by mkambol** [comment]
@mbatchelor You're right, this really should have a test.  That was a miss on my part.
@YuryBY take a pass at adding tests for this.  It's possible you could use a strategy similar to what was done with a9107ab
Or possibly we could test the nonEmptyList method directly by running a query and grabbing an evaluator and list to use for the test.
Let me know if you get stuck and I can assist.

**Pull request merged**
