### PR TITLE
[MONDRIAN-2597]: readTuples and cardinality queries sent twice to the…

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
… database when using Virtual Cube (Not cached)

Fixed the twice sending of readTuples query to the DB.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@lucboudreau , @mkambol please review the fix for the part related with duplicating `readTuples`.

**Comment by mkambol** [comment]
@TatsianaKasiankova -  it feels to me like the list of base cubes should be something you should be able to learn from the Virtual cube itself.  That is, instead of spreading the logic for getting/setting the list of base cubes across mutable fields in the Query and special purpose logic in SqlContextConstraint, is there a way we could include it in RolapCube?  RolapCube already has a .isVirtual method.  Seems like it would be reasonable to also have a .baseCubes() method.  That would also be a consistent way of getting the info, regardless of whether native eval is in use or not (SqlContextConstraint won't be used with non-native).

@kurtwalker - I know you looked at this earlier, would be curious if you have an opinion.

**Comment by mkambol** [comment]
Oh, also-  could you add one or more tests?

**Comment by kurtwalker** [comment]
I agree, it could go on RolapCube and be a lazy-loaded getter.  In the case where it's not virtual, could just return this;

**Comment by TatsianaKasiankova** [comment]
@lucboudreau , @mkambol , @kurtwalker please review the fix.

**Pull request merged**
