### PR TITLE
[PSW-278] - List of dialects not sorted correctly

### PR DESCRIPTION
**Pull request by joana-fb**
@pentaho/tatooine_dev

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl workbench
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by befc** [comment]
The change looks good, and would fix the current bug, but it's not a good practice to rely on the order of the items in a configuration file to be displayed to the user. If the expected order is sorted, why not sort it before it's displayed, or even better, wherever the list of values is being stored in memory upon read? This will avoid us dealing with this kind of bugs again

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -DrunITs -pl workbench
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by befc — APPROVED** [review]

**Pull request merged**
