### PR TITLE
[MONDRIAN-2496] - Parent/child use captionColumn

### PR DESCRIPTION
**Pull request by martijn-basesoft**
Fix with testcase for MONDRIAN-2496

### CODE REVIEW

**Comment by kurtwalker** [comment]
if you could change your commit message to the format "[MONDRIAN-2496] - Parent/child use captionColumn" that will help our tracking.  thanks.

**Comment by martijn-basesoft** [comment]
done!

**Comment by martijn-basesoft** [comment]
I noticed the new RolapMemberBase was created after a .setCaption was called, but that information isn't passed. I moved the .setCaption() after the new member is created so all members get that call now.  This makes the failing tests pass for me again. What do you think of this change?

**Comment by kurtwalker** [comment]
I don't follow how this would change anything since it was previously being set on the dataMember which is ultimately what's used to get the caption anyway.  Can you help me understand?  I'm hesitant to merge because it has a potential to affect other code paths.

**Comment by martijn-basesoft** [comment]
It seems if we override getCaption() in RolapParentChildMember then the xmla tests executeHR seem to fail because they use a closure table on the HR Cube that has a nameColumn (and no captionColumn) set. 

With getCaption() overriden, it then calls dataMember.getCaption() which (because caption equals null) calls getName() in OlapElementBase. It then returns the value (integer) in these xmla tests, and thats wrong. 

I noticed if I move the .setCaption() after the parent-child member is created then the getName() behaviour is equal in both cases and no getCaption() override is needed. 

We can keep the .getCaption() override but I'll need a hint how to fix the getName() issue in case of nameColumn set. Any hints where to look for?

**Pull request closed without merging**
