### PR TITLE
MONDRIAN-2366 - CacheControl.flush(MemberSet) does not flush NativeSet member caches.

### PR DESCRIPTION
**Pull request by YuryBY**
@mkambol, @lucboudreau, take a look, please

### CODE REVIEW

**Comment by lucboudreau** [comment]
@mkambol Please review this PR. From a quick review, I can already tell it'll need to be reworked a bit since none of the changes are thread-safe.

**Comment by mkambol** [comment]
@lucboudreau @YuryBY 
The thing that caught my eye is the implementation of .flushCache, which checks for cache size before clearing.  There's no need to check size, so that could just be a call to .clear() to avoid needing to lock.
The cache itself uses a ReentrantReadWriteLock for all operations, so I think the call to .clear() itself requires no extra handing.
Anything else you were seeing, Luc?

**Comment by lucboudreau** [comment]
The method flushAllNativeSetCache iterates over elements. Is this also protected by the RRWL?

**Comment by mkambol** [comment]
No, but the nativeEvaluatorMap that it's iterating over is a fixed map set at construction of the registry.  For correctness I'd say that should be made an ImmutableMap.

**Comment by YuryBY** [comment]
@mkambol, @lucboudreau, PR is already updated

- there was no possibility to use unmodifiablemap because of the https://github.com/YuryBY/mondrian/blob/master/src/main/mondrian/rolap/RolapNativeRegistry.java#L79 method (is supposed calling from external point). My solution is ReentrantReadWriteLock

**Comment by mkambol** [comment]
@YuryBY - My guess is nobody is using the register method, but I guess better safe then sorry.

What about using a ConcurrentHashMap instead of introducing the read and write locks in each method in RolapNativeRegistry?

**Comment by YuryBY** [comment]
@mkambol - places where I'm not sure about ConcurrentHashMap are iterator usages (https://github.com/pentaho/mondrian/pull/498/files#diff-64c6891e7df227db892341b4505175d0R116, https://github.com/pentaho/mondrian/pull/498/files#diff-64c6891e7df227db892341b4505175d0R93, https://github.com/pentaho/mondrian/pull/498/files#diff-64c6891e7df227db892341b4505175d0R105).  Thread-safety will work fine here but thread while iterating will not see changes in map which can be done by another one thread (by using of put or remove methods). If it's appropriate behavior I'll replace ReentrantReadWriteLock by ConcurrentHashMap. Thanks, Yury.

**Pull request merged**
